name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^2.2.0
  geolocator: ^11.0.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/sunny_animation.json
  - assets/rainy_animation.json
  - assets/thunder_animation.json
  - assets/cloudy_animation.json
